apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: test-api-dev
spec:
  selector:
    app: myapp
  ports:
    - port: 8085
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: kaushikrahul08/webapp:v1.7
        ports:
        - containerPort: 8000
