apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: test-api-dev
spec:
  selector:
    app: myapp
  ports:
    - port: 8085
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service test-api-dev"]'
  labels:
    tier: frontend
  name: frontend
  namespace: test-api-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - image: kaushikrahul08/webapp
          name: frontend
          ports:
            - containerPort: 8000
